### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by iTakeshi** [NB-DQN/maze_generator#1]
- [x] commanline runner
- [x] generator
  - [x] backtracking core algorithm
  - [x] create exit
  - [x] rearrange field from 2N+3 x 2M+3 to NxM
- [ ] maze object methods
  - [x] wall information for given coordinate
  - [x] judgement for completion
  - [x] display in CUI
  - [ ] display in GUI
- [ ] unit test (planning)
